CREATE TABLE public.agent_job (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    created_by text NOT NULL,
    task_type text NOT NULL,
    prompt text NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    runner text DEFAULT 'claw-cli'::text NOT NULL,
    session_dir text,
    result jsonb,
    error text,
    cancel_requested boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agent_job_prompt_check CHECK (length(TRIM(BOTH FROM prompt)) > 0),
    CONSTRAINT agent_job_runner_check CHECK (length(TRIM(BOTH FROM runner)) > 0),
    CONSTRAINT agent_job_status_check CHECK (
        status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])
    ),
    CONSTRAINT agent_job_task_type_check CHECK (
        task_type = ANY (
            ARRAY[
                'project_qa'::text,
                'standard_import_assist'::text,
                'document_archive_assist'::text,
                'tag_search_assist'::text,
                'drawing_analysis_assist'::text
            ]
        )
    )
);

COMMENT ON TABLE public.agent_job IS 'Project-scoped AI agent jobs executed through isolated sidecar runners.';
COMMENT ON COLUMN public.agent_job.created_by IS 'Authenticated user id captured as text for audit compatibility with external identity providers.';
COMMENT ON COLUMN public.agent_job.result IS 'Final structured draft result from the runner. Business writes must still go through normal APIs.';

CREATE TABLE public.agent_job_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    seq integer NOT NULL,
    event_type text NOT NULL,
    message text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agent_job_event_event_type_check CHECK (length(TRIM(BOTH FROM event_type)) > 0),
    CONSTRAINT agent_job_event_seq_check CHECK (seq > 0)
);

COMMENT ON TABLE public.agent_job_event IS 'Append-only event log used as the source of truth for SSE replay.';

CREATE TABLE public.agent_artifact (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    artifact_type text NOT NULL,
    title text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agent_artifact_artifact_type_check CHECK (length(TRIM(BOTH FROM artifact_type)) > 0),
    CONSTRAINT agent_artifact_status_check CHECK (status = ANY (ARRAY['draft'::text, 'accepted'::text, 'rejected'::text])),
    CONSTRAINT agent_artifact_title_check CHECK (length(TRIM(BOTH FROM title)) > 0)
);

COMMENT ON TABLE public.agent_artifact IS 'Draft artifacts generated by agent jobs. Users must explicitly accept before business data changes.';

ALTER TABLE ONLY public.agent_job
    ADD CONSTRAINT agent_job_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_job_event
    ADD CONSTRAINT agent_job_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_job_event
    ADD CONSTRAINT agent_job_event_seq_key UNIQUE (job_id, seq);

ALTER TABLE ONLY public.agent_artifact
    ADD CONSTRAINT agent_artifact_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_job
    ADD CONSTRAINT agent_job_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_job_event
    ADD CONSTRAINT agent_job_event_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.agent_job(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_artifact
    ADD CONSTRAINT agent_artifact_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.agent_job(id) ON DELETE CASCADE;

CREATE INDEX agent_job_project_status_created_by_created_at_idx
    ON public.agent_job USING btree (project_id, status, created_by, created_at DESC);

CREATE INDEX agent_job_created_by_status_created_at_idx
    ON public.agent_job USING btree (created_by, status, created_at DESC);

CREATE INDEX agent_job_event_job_id_seq_idx
    ON public.agent_job_event USING btree (job_id, seq);

CREATE INDEX agent_artifact_job_id_created_at_idx
    ON public.agent_artifact USING btree (job_id, created_at DESC);

CREATE TRIGGER agent_job_set_updated_at BEFORE UPDATE ON public.agent_job
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
